"""baseline schema

Adopts the pre-Alembic schema (previously built with ``create_all``) as the
Alembic baseline. ``upgrade`` builds the full current schema from the models so
a fresh database comes up identically; ``downgrade`` drops it. Future schema
changes are separate autogenerated revisions on top of this baseline.

Revision ID: 0001
Revises:
Create Date: 2026-07-14
"""
from alembic import op

from app.models import Base

# revision identifiers, used by Alembic.
revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # checkfirst=True (default) makes this a no-op on a DB that already has the
    # tables — harmless if run against a legacy DB before it was stamped.
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
