"""add obligation direction and occurrence paid_date

Revision ID: 4811131e840e
Revises: eae3e0b50af2
Create Date: 2026-07-15 13:59:56.288765
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4811131e840e'
down_revision = 'eae3e0b50af2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills any pre-existing rows (matches the model's
    # Python-side default so new rows behave the same without relying on it).
    op.add_column(
        'obligation',
        sa.Column('direction', sa.String(length=10), nullable=False, server_default='payable'),
    )
    op.add_column('obligation_occurrence', sa.Column('paid_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('obligation_occurrence', 'paid_date')
    op.drop_column('obligation', 'direction')
    # ### end Alembic commands ###
