"""add obligation_group and occurrence period

Revision ID: d1201df0f1f8
Revises: 4811131e840e
Create Date: 2026-07-15 15:27:44.319453
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1201df0f1f8'
down_revision = '4811131e840e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obligation_group',
    sa.Column('obligation_group_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('recurrence', sa.String(length=10), nullable=True),
    sa.Column('expected_day_of_month', sa.Integer(), nullable=True),
    sa.Column('expected_weekday', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.PrimaryKeyConstraint('obligation_group_id')
    )
    op.create_index(op.f('ix_obligation_group_name'), 'obligation_group', ['name'], unique=False)
    op.add_column('obligation', sa.Column('obligation_group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'obligation', 'obligation_group', ['obligation_group_id'], ['obligation_group_id'])
    op.add_column('obligation_occurrence', sa.Column('period', sa.String(length=7), nullable=True))
    op.create_index(op.f('ix_obligation_occurrence_period'), 'obligation_occurrence', ['period'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_obligation_occurrence_period'), table_name='obligation_occurrence')
    op.drop_column('obligation_occurrence', 'period')
    op.drop_constraint(None, 'obligation', type_='foreignkey')
    op.drop_column('obligation', 'obligation_group_id')
    op.drop_index(op.f('ix_obligation_group_name'), table_name='obligation_group')
    op.drop_table('obligation_group')
    # ### end Alembic commands ###
