"""add obligations

Revision ID: eae3e0b50af2
Revises: 754a2769136d
Create Date: 2026-07-15 05:39:22.309494
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eae3e0b50af2'
down_revision = '754a2769136d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obligation_import_format',
    sa.Column('obligation_import_format_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('sheet_name', sa.String(length=255), nullable=True),
    sa.Column('header_row', sa.Integer(), nullable=False),
    sa.Column('date_format', sa.String(length=50), nullable=True),
    sa.Column('decimal_separator', sa.String(length=1), nullable=False),
    sa.Column('default_recurrence', sa.String(length=10), nullable=True),
    sa.Column('default_category_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['default_category_id'], ['category.category_id'], ),
    sa.PrimaryKeyConstraint('obligation_import_format_id')
    )
    op.create_table('obligation',
    sa.Column('obligation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('payee_id', sa.Integer(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurrence', sa.String(length=10), nullable=True),
    sa.Column('estimated_amount', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_via_format_id', sa.Integer(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('duplicate_of_obligation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.ForeignKeyConstraint(['created_via_format_id'], ['obligation_import_format.obligation_import_format_id'], ),
    sa.ForeignKeyConstraint(['duplicate_of_obligation_id'], ['obligation.obligation_id'], ),
    sa.ForeignKeyConstraint(['payee_id'], ['payee.payee_id'], ),
    sa.PrimaryKeyConstraint('obligation_id')
    )
    op.create_table('obligation_import_format_field',
    sa.Column('obligation_import_format_field_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('obligation_import_format_id', sa.Integer(), nullable=False),
    sa.Column('target_field', sa.String(length=30), nullable=False),
    sa.Column('source_column', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['obligation_import_format_id'], ['obligation_import_format.obligation_import_format_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('obligation_import_format_field_id')
    )
    op.create_table('obligation_occurrence',
    sa.Column('obligation_occurrence_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('obligation_id', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('estimated_amount', sa.Float(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_via_format_id', sa.Integer(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('duplicate_of_occurrence_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_via_format_id'], ['obligation_import_format.obligation_import_format_id'], ),
    sa.ForeignKeyConstraint(['duplicate_of_occurrence_id'], ['obligation_occurrence.obligation_occurrence_id'], ),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligation.obligation_id'], ),
    sa.PrimaryKeyConstraint('obligation_occurrence_id')
    )
    op.create_table('obligation_occurrence_transaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('obligation_occurrence_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['obligation_occurrence_id'], ['obligation_occurrence.obligation_occurrence_id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.transaction_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    # ### end Alembic commands ###

    # Manually added (autogenerate doesn't add these without index=True on the
    # model columns): supports the dedup name lookup and occurrence listing/
    # upcoming-due-date queries.
    op.create_index('ix_obligation_name', 'obligation', ['name'])
    op.create_index('ix_obligation_occurrence_obligation_id', 'obligation_occurrence', ['obligation_id'])
    op.create_index('ix_obligation_occurrence_due_date', 'obligation_occurrence', ['due_date'])


def downgrade() -> None:
    op.drop_index('ix_obligation_occurrence_due_date', table_name='obligation_occurrence')
    op.drop_index('ix_obligation_occurrence_obligation_id', table_name='obligation_occurrence')
    op.drop_index('ix_obligation_name', table_name='obligation')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('obligation_occurrence_transaction')
    op.drop_table('obligation_occurrence')
    op.drop_table('obligation_import_format_field')
    op.drop_table('obligation')
    op.drop_table('obligation_import_format')
    # ### end Alembic commands ###
